### ISSUE TITLE
Create User Profile

### ISSUE THREAD

**Issue by Gareth-McGirr** [Gareth-McGirr/body-doodles-api#10]
**User Story**

As a developer, I want to create a new blank profile with default image when a user is created.

**Acceptance Criteria**

A new profile is created when a user is created

**Tasks**
- [x] Create profiles app
- [x]  Add to installed apps in settings.py
- [x]  create Profile model
- [x] add signal to create a blank profile when user is created with a default profile image
