### ISSUE TITLE
View User Profile

### ISSUE THREAD

**Issue by Gareth-McGirr** [Gareth-McGirr/body-doodles-api#13]
**User Story**

As a user, I want to able to view a profile

**Acceptance Criteria**

- A single profile is returned based on the id
- 404 error if profile not found

**Tasks**
- [ ] write a profile detail view
- [ ] define get method
- [ ] add view to urls.py
