### ISSUE TITLE
Add google cloud storage for static images

### ISSUE THREAD

**Issue by Gareth-McGirr** [Gareth-McGirr/body-doodles-api#3]
**User Story**

As a developer, I need to create the google cloud bucket and create the connection to the project so that static images can be uploaded by users.

**Acceptance Criteria**

- Cloud Storage connected to project locally

**Tasks** 
- [ ] Create Cloud Storage bucket
- [ ] Create Service Account with permissions for **create** and **read** access on Cloud Storage
- [ ] Install django_storages[google] and pillow and update requirements
- [ ] Update settings.py to use google as default file storage
