### ISSUE TITLE
Create and list posts

### ISSUE THREAD

**Issue by Gareth-McGirr** [Gareth-McGirr/body-doodles-api#5]
**User Story**

As a user, I want to able to create a post and list posts

**Acceptance Criteria**

A new post can be created
A list of posts can be returned

**Tasks**
- [x] create post app
- [x] create post model
- [x]  write a model serializer for Post
- [x] Add image filter and validation
- [x] Create PostList view
- [x] create get method  
- [x] create post method
