### ISSUE TITLE
View, Edit, Delete a Post

### ISSUE THREAD

**Issue by Gareth-McGirr** [Gareth-McGirr/body-doodles-api#6]
**User Story**

As a user, I want to able to view, edit or delete a post

**Acceptance Criteria**
A post can be retrieved by its id
A post can be edited if the logged in user is owner of the post
A post can be deleted if the logged in user is the owner of the post

**Tasks**
- [x] create PostDetailView
- [x] create get method
- [x] create put method
- [x] create delete method
